const dbProjects = [
  {
    "name": "Central Vista Avenue",
    "client": "Shapoorji Pallonji Construction Limited",
    "location": "New Delhi",
    "country": "India",
    "continent": "Asia",
    "lat": "28.6131",
    "lon": "77.2295",
    "description": "Redevelopment of the historic power corridor of India.",
    "scope of work": "Complete Landscape, Civil, UG services modelling; Clash Detection and resolution; Quantity Take-offs; 4D simulation",
    "image": "null",
    "awards": ""
  },
  {
    "name": "Bharat Mandapam",
    "client": "ARCOP Architects",
    "location": "New Delhi",
    "country": "India",
    "continent": "Asia",
    "lat": "28.6127",
    "lon": "77.2433",
    "description": "International Exhibition-cum-Convention Centre (IECC).",
    "scope of work": "Architecture and Structure modelling; Clash Detection and resolution; Design Coordination",
    "image": "null",
    "awards": ""
  },
  {
    "name": "Leela Palace",
    "client": "Leela Hotels & Brookfield Properties",
    "location": "Bengaluru",
    "country": "India",
    "continent": "Asia",
    "lat": "12.9716",
    "lon": "77.5946",
    "description": "Luxury hospitality project requiring high-precision as-built documentation.",
    "scope of work": "Laser Scanning; As-built drawings; Proposed modelling and design coordination; Shop drawings",
    "image": "https://static.wixstatic.com/media/15cdbf_cfcb7f9c20434c639bbc596ac5750a29~mv2.png/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_cfcb7f9c20434c639bbc596ac5750a29~mv2.png",
    "awards": ""
  },
  {
    "name": "Godrej RK Studio",
    "client": "Godrej Properties Limited",
    "location": "Mumbai",
    "country": "India",
    "continent": "Asia",
    "lat": "19.076",
    "lon": "72.8777",
    "description": "Mixed-use redevelopment of the iconic RK Studios site.",
    "scope of work": "Complete ASMEP modeling; Clash Detection and resolution; Value Engineering; Quantity Extraction; Coordinated Drawings",
    "image": "https://static.wixstatic.com/media/15cdbf_34c083389ae4417099292a1ef87adc10~mv2.jpg/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_34c083389ae4417099292a1ef87adc10~mv2.jpg",
    "awards": ""
  },
  {
    "name": "Godrej Ashok Vihar",
    "client": "Godrej Properties Limited",
    "location": "Delhi",
    "country": "India",
    "continent": "Asia",
    "lat": "28.6946",
    "lon": "77.1728",
    "description": "Residential development in North Delhi.",
    "scope of work": "BIM Execution Plan; BIM Management; Clash Detection and resolution; 4D- Schedule Simulation; 5D- Quantity Extraction",
    "image": "https://static.wixstatic.com/media/15cdbf_5f225acf93354b87a984eabd32b7a72b~mv2.jpg/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_5f225acf93354b87a984eabd32b7a72b~mv2.jpg",
    "awards": ""
  },
  {
    "name": "Signature Tower",
    "client": "Godrej Fund Management & Century Real Estate",
    "location": "Bengaluru",
    "country": "India",
    "continent": "Asia",
    "lat": "12.9716",
    "lon": "77.5946",
    "description": "Grade-A commercial office space development.",
    "scope of work": "Complete ASMEP modeling; Clash Detection and resolution; Value Engineering; Quantity Extraction; Coordinated Drawings",
    "image": "https://static.wixstatic.com/media/15cdbf_7a874801285d4c57a794eb6bf074c4de~mv2.png/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_7a874801285d4c57a794eb6bf074c4de~mv2.png",
    "awards": ""
  },
  {
    "name": "Elan Imperial",
    "client": "Elan Group",
    "location": "Gurugram",
    "country": "India",
    "continent": "Asia",
    "lat": "28.4595",
    "lon": "77.0266",
    "description": "Commercial and retail development in the heart of Gurugram.",
    "scope of work": "Complete ASMEP modeling; Clash Detection and resolution; Value Engineering; Quantity Extraction",
    "image": "null",
    "awards": ""
  },
  {
    "name": "Birla Arika",
    "client": "Birla Estate",
    "location": "Gurugram",
    "country": "India",
    "continent": "Asia",
    "lat": "28.4595",
    "lon": "77.0266",
    "description": "Premium residential project in Sector 31.",
    "scope of work": "BIM Execution Planning; BIM Management; BIM Audits; Quantity Take-off",
    "image": "null",
    "awards": ""
  },
  {
    "name": "Godrej GCR",
    "client": "Godrej Fund Management",
    "location": "Gurugram",
    "country": "India",
    "continent": "Asia",
    "lat": "28.4595",
    "lon": "77.0266",
    "description": "Modern commercial office complex development.",
    "scope of work": "BIM Execution Plan; BIM Management & BIM Audits; Clash Detection and resolution; 4D- Schedule Simulation; 5D- Quantity Extraction",
    "image": "null",
    "awards": ""
  },
  {
    "name": "WHO Building",
    "client": "NBCC / Parnika Contractors",
    "location": "New Delhi",
    "country": "India",
    "continent": "Asia",
    "lat": "28.6139",
    "lon": "77.209",
    "description": "Healthcare administrative building for the World Health Organization.",
    "scope of work": "Complete ASMEP modeling; Clash Detection and resolution; Value Engineering; Quantity Extraction; Coordinated Drawings",
    "image": "null",
    "awards": ""
  },
  {
    "name": "DLF Data Center",
    "client": "DLF Limited",
    "location": "NOIDA",
    "country": "India",
    "continent": "Asia",
    "lat": "28.5355",
    "lon": "77.391",
    "description": "High-tier data storage facility requiring complex MEP coordination.",
    "scope of work": "Complete ASMEP modeling; Clash Detection and resolution; Value Engineering; Quantity Extraction; Coordinated Drawings",
    "image": "https://static.wixstatic.com/media/15cdbf_6f3fc1611bd84d76b57aea085c2e941a~mv2.jpg/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_6f3fc1611bd84d76b57aea085c2e941a~mv2.jpg",
    "awards": ""
  },
  {
    "name": "Max House",
    "client": "Max Ventures",
    "location": "Okhla, New Delhi",
    "country": "India",
    "continent": "Asia",
    "lat": "28.5447",
    "lon": "77.2721",
    "description": "Boutique commercial office building.",
    "scope of work": "Complete ASMEP modeling; Clash Detection and resolution; Value Engineering; Quantity Extraction; Coordinated Drawings",
    "image": "null",
    "awards": ""
  },
  {
    "name": "Bharti Worldmark",
    "client": "Bharti Realty",
    "location": "Gurugram",
    "country": "India",
    "continent": "Asia",
    "lat": "28.4595",
    "lon": "77.0266",
    "description": "Commercial and retail hub with a focus on design and sustainability.",
    "scope of work": "Architecture, Structure and MEP modeling; Clash Detection and Design Coordination; ASMEP Quantities; MEP Shop Drawings; Rebar modeling & BBS",
    "image": "https://static.wixstatic.com/media/15cdbf_cb0bed4b63cf4484b55d15af39773701~mv2.png/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_cb0bed4b63cf4484b55d15af39773701~mv2.png",
    "awards": ""
  },
  {
    "name": "Warehouse for Flipkart",
    "client": "Flipkart",
    "location": "Kolkata",
    "country": "India",
    "continent": "Asia",
    "lat": "22.5726",
    "lon": "88.3639",
    "description": "Large scale logistics and warehousing facility.",
    "scope of work": "Architecture, Structure and MEP modeling; Racking and Conveyor System modeling; Clash Detection and Design Coordination; Quantity extraction",
    "image": "null",
    "awards": ""
  },
  {
    "name": "Marriott Combo Hotel",
    "client": "Marriott International",
    "location": "Bengaluru",
    "country": "India",
    "continent": "Asia",
    "lat": "12.9716",
    "lon": "77.5946",
    "description": "Hospitality development featuring multiple Marriott brands.",
    "scope of work": "Basement, Ground, Service, Guest Room Floor; LOD 300 Architecture & Structure model; LOD 400 detailed MEP Modeling; Clash Detection and Design Coordination; MEP Shop Drawings and Quantities",
    "image": "https://static.wixstatic.com/media/15cdbf_2ca19ce5ccd74cf0b8926c5f6d4eb86d~mv2.jpg/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_2ca19ce5ccd74cf0b8926c5f6d4eb86d~mv2.jpg",
    "awards": ""
  },
  {
    "name": "Precinct 2 & 3, Bhartiya City",
    "client": "Bhartiya City Developers",
    "location": "Bengaluru",
    "country": "India",
    "continent": "Asia",
    "lat": "13.0617",
    "lon": "77.6253",
    "description": "Integrated township and commercial precinct development.",
    "scope of work": "LOD 300 Architecture & Structure model; LOD 300 MEP Modeling; Clash Detection and Design Coordination; MEP Shop Drawings and Quantities",
    "image": "null",
    "awards": ""
  },
  {
    "name": "IREO Gurgaon Hills",
    "client": "IREO Pvt. Ltd.",
    "location": "Gurugram",
    "country": "India",
    "continent": "Asia",
    "lat": "28.4595",
    "lon": "77.0266",
    "description": "Luxury residential development in Gurugram.",
    "scope of work": "Architecture, Structure and MEP modeling; Clash Detection; Design Coordination; Value Engineering; ASMEP Quantities",
    "image": "null",
    "awards": ""
  },
  {
    "name": "IREO FiveRivers Township",
    "client": "IREO Fiverivers Pvt. Ltd.",
    "location": "Panchkula",
    "country": "India",
    "continent": "Asia",
    "lat": "30.6942",
    "lon": "76.8606",
    "description": "Expansive residential township development.",
    "scope of work": "BIM Implementation and design validation.",
    "image": "null",
    "awards": ""
  },
  {
    "name": "Capital Tower 1",
    "client": "EMAAR MGF",
    "location": "Gurugram",
    "country": "India",
    "continent": "Asia",
    "lat": "28.4595",
    "lon": "77.0266",
    "description": "High-rise commercial office tower.",
    "scope of work": "Architecture, Structure and MEP modeling; Site modeling; Clash Detection and Design Coordination; ASMEP Quantities",
    "image": "https://static.wixstatic.com/media/15cdbf_cc3afe74eeb74cd5b339a436b7e59150~mv2.jpg/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_cc3afe74eeb74cd5b339a436b7e59150~mv2.jpg",
    "awards": ""
  },
  {
    "name": "Capital Tower 2",
    "client": "EMAAR MGF",
    "location": "Gurugram",
    "country": "India",
    "continent": "Asia",
    "lat": "28.4595",
    "lon": "77.0266",
    "description": "Secondary phase of the Capital Tower commercial development.",
    "scope of work": "Architecture, Structure and MEP modeling; Site modeling; Clash Detection and Design Coordination; ASMEP Quantities",
    "image": "https://static.wixstatic.com/media/15cdbf_49c48404900044db9b1539c5860e5e34~mv2.png/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_49c48404900044db9b1539c5860e5e34~mv2.png",
    "awards": ""
  },
  {
    "name": "Godrej Icon",
    "client": "Colliers International & Godrej Properties",
    "location": "Gurugram",
    "country": "India",
    "continent": "Asia",
    "lat": "28.4595",
    "lon": "77.0266",
    "description": "Residential skyscraper project.",
    "scope of work": "Architecture and Structure modeling; Architectural and Structural BIM-extracted quantities",
    "image": "null",
    "awards": ""
  },
  {
    "name": "Godrej Oasis",
    "client": "Colliers International & Godrej Properties",
    "location": "Gurugram",
    "country": "India",
    "continent": "Asia",
    "lat": "28.4595",
    "lon": "77.0266",
    "description": "Modern residential complex.",
    "scope of work": "Architecture and Structure modeling; Architectural and Structural BIM-extracted quantities",
    "image": "https://static.wixstatic.com/media/15cdbf_ded86416295b47f89345691e351653af~mv2.png/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_ded86416295b47f89345691e351653af~mv2.png",
    "awards": ""
  },
  {
    "name": "The City University of New York",
    "client": "F J Sciame Construction LLC, New York",
    "location": "NY",
    "country": "USA",
    "continent": "North America",
    "lat": "40.7128",
    "lon": "-74.006",
    "description": "Academic building expansion and modernization.",
    "scope of work": "Updating architecture and structure BIM models; Revision & Model management during construction; Clash detection and design coordination; Bid support for Client's BIM team",
    "image": "https://static.wixstatic.com/media/15cdbf_19b1eef9651c443f8d579430a71c31b0~mv2.png/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_19b1eef9651c443f8d579430a71c31b0~mv2.png",
    "awards": ""
  },
  {
    "name": "The Shed",
    "client": "F J Sciame Construction LLC, New York",
    "location": "NY",
    "country": "USA",
    "continent": "North America",
    "lat": "40.7128",
    "lon": "-74.006",
    "description": "Cultural center in Hudson Yards with a unique moving outer shell.",
    "scope of work": "Updating architecture and structure BIM models; Revision & Model management during construction; Clash detection and design coordination; Bid support for Client's BIM team",
    "image": "https://static.wixstatic.com/media/15cdbf_d3ec78f769db4dc6afe1e9850935bcf0~mv2.jpg/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_d3ec78f769db4dc6afe1e9850935bcf0~mv2.jpg",
    "awards": ""
  },
  {
    "name": "City Block Façade Redevelopment",
    "client": "PLANiT Measuring-Artex",
    "location": "Manhattan, NYC",
    "country": "USA",
    "continent": "North America",
    "lat": "40.7831",
    "lon": "-73.9712",
    "description": "Redevelopment of a city block facade using precast panels.",
    "scope of work": "Creation of BIM for precast concrete Façade panels; Validating shop drawing prepared by sub; Clash detection with existing site steel; Visualization support",
    "image": "null",
    "awards": ""
  },
  {
    "name": "Apartments in Bethesda",
    "client": "Private Developer",
    "location": "Maryland",
    "country": "USA",
    "continent": "North America",
    "lat": "39.0458",
    "lon": "-76.6413",
    "description": "Residential multi-family development.",
    "scope of work": "Architecture and Structure BIM Modeling and Design Coordination.",
    "image": "https://static.wixstatic.com/media/15cdbf_4537bf85c08b46728a66fd92b68f32dd~mv2.jpg/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_4537bf85c08b46728a66fd92b68f32dd~mv2.jpg",
    "awards": ""
  },
  {
    "name": "Kuwait Cancer Hospital",
    "client": "Gulf Consult & NBBJ",
    "location": "Kuwait City",
    "country": "Kuwait",
    "continent": "Asia",
    "lat": "29.3759",
    "lon": "47.9774",
    "description": "Specialized healthcare facility with complex medical systems.",
    "scope of work": "Structure & MEP modeling, Arch updation; Clash Detection and Design Coordination; Design Optimization; DD & CD Stage drawing production",
    "image": "https://static.wixstatic.com/media/15cdbf_fe56117de4e546b4870f75287efa77a7~mv2.jpg/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_fe56117de4e546b4870f75287efa77a7~mv2.jpg",
    "awards": ""
  },
  {
    "name": "The Atria Residential Towers",
    "client": "Deyaar Development",
    "location": "Dubai",
    "country": "UAE",
    "continent": "Asia",
    "lat": "25.2048",
    "lon": "55.2708",
    "description": "Twin-tower residential development in Business Bay.",
    "scope of work": "Virtual Construction-Architecture, Structure & MEP; Clash Detection and Design Coordination; BIM-extracted quantities; MEP Shop Drawings",
    "image": "https://static.wixstatic.com/media/15cdbf_481ede156f7a472f975b9e66bec26f6c~mv2.png/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_481ede156f7a472f975b9e66bec26f6c~mv2.png",
    "awards": ""
  },
  {
    "name": "Case Study of Hospital Drywall Partition Drawings",
    "client": "Healthcare Provider",
    "location": "USA",
    "country": "USA",
    "continent": "North America",
    "lat": "37.0902",
    "lon": "-95.7129",
    "description": "Technical coordination study for drywall systems in healthcare.",
    "scope of work": "Prepare partition system BIM model; Coordinate framing with MEP & medical gases system; Produce detailed drywall partition floor plan drawings; Produce detailed drywall partition elevation drawings",
    "image": "null",
    "awards": ""
  },
  {
    "name": "Villa Development at Riyadh",
    "client": "Al Akaria Real Estate Company",
    "location": "Riyadh",
    "country": "Kingdom of Saudi Arabia",
    "continent": "Asia",
    "lat": "24.7136",
    "lon": "46.6753",
    "description": "Large-scale luxury villa residential complex.",
    "scope of work": "Virtual Construction-Architecture, Structure & MEP modeling for typical villas; Clash Detection and Design Coordination; BIM-extracted quantities; Value Engineering; MEP Shop Drawings",
    "image": "null",
    "awards": ""
  },
  {
    "name": "Dalian City Tower",
    "client": "Dalian Star Properties",
    "location": "Dalian City",
    "country": "China",
    "continent": "Asia",
    "lat": "38.914",
    "lon": "121.6146",
    "description": "High-rise commercial tower with detailed FM requirements.",
    "scope of work": "As-built Architecture, Structure & MEP BIM; As-built drawing extraction for FM and O&M; 3D Views for interior renovation planning; Digital asset with tap-off connection details",
    "image": "null",
    "awards": ""
  },
  {
    "name": "Al Maktoum International Airport",
    "client": "Dubai Airports",
    "location": "Dubai",
    "country": "UAE",
    "continent": "Asia",
    "lat": "24.8943",
    "lon": "55.1587",
    "description": "Major international aviation hub expansion.",
    "scope of work": "Architecture, Structure, MEP Modelling; Clash Detection and design coordination; Design and construction drawing",
    "image": "null",
    "awards": ""
  },
  {
    "name": "Athens International Airport",
    "client": "Athens International Airport S.A.",
    "location": "Athens",
    "country": "Greece",
    "continent": "Europe",
    "lat": "37.9356",
    "lon": "23.9484",
    "description": "Facade redevelopment for the airport terminal.",
    "scope of work": "Façade modelling; Design Coordination with Architecture, Structure, MEP; Design and facade drawing",
    "image": "null",
    "awards": ""
  },
  {
    "name": "Cruise Terminal Building, Ft. Lauderdale",
    "client": "Port Everglades",
    "location": "Florida",
    "country": "USA",
    "continent": "North America",
    "lat": "26.1224",
    "lon": "-80.1373",
    "description": "Cruise infrastructure facility.",
    "scope of work": "Complete LOD 400 MEP modelling; Clash detection and Design Coordination; Plumbing Shop drawings",
    "image": "null",
    "awards": ""
  },
  {
    "name": "Terminal 6 Building JFK Airport",
    "client": "Hirani Group, New York",
    "location": "NYC",
    "country": "USA",
    "continent": "North America",
    "lat": "40.7128",
    "lon": "-74.006",
    "description": "Structural renovation and expansion of JFK Terminal 6.",
    "scope of work": "Structural modeling; Structural Model editing; Structural modelling; Scan to BIM; Structural model updation",
    "image": "https://static.wixstatic.com/media/15cdbf_36f173177fb24bf08f7a0412fb0184b2~mv2.png/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_36f173177fb24bf08f7a0412fb0184b2~mv2.png",
    "awards": ""
  },
  {
    "name": "Lucknow International Airport",
    "client": "AAI / Adani Airports",
    "location": "Lucknow",
    "country": "India",
    "continent": "Asia",
    "lat": "26.7606",
    "lon": "80.8893",
    "description": "Infrastructure asset management and BIM implementation.",
    "scope of work": "Architecture, Structure, MEP Modelling; Scan to BIM, As-built data tagging; Asset Information Modelling",
    "image": "null",
    "awards": ""
  },
  {
    "name": "Ahmedabad International Airport",
    "client": "AAI / Adani Airports",
    "location": "Ahmedabad",
    "country": "India",
    "continent": "Asia",
    "lat": "23.0772",
    "lon": "72.6347",
    "description": "Asset information modelling for existing airport facilities.",
    "scope of work": "Architecture, Structure, MEP Modelling; Scan to BIM, As-built data tagging; Asset Information Modelling",
    "image": "null",
    "awards": ""
  },
  {
    "name": "Mumbai International Airport",
    "client": "AAI / Adani Airports",
    "location": "Mumbai",
    "country": "India",
    "continent": "Asia",
    "lat": "19.0896",
    "lon": "72.8656",
    "description": "Digitization of airport assets for operations and maintenance.",
    "scope of work": "Architecture, Structure, MEP Modelling; Scan to BIM, As-built data tagging; Asset Information Modelling",
    "image": "null",
    "awards": ""
  },
  {
    "name": "Mangaluru International Airport",
    "client": "AAI / Adani Airports",
    "location": "Mangaluru",
    "country": "India",
    "continent": "Asia",
    "lat": "12.9613",
    "lon": "74.8891",
    "description": "Scan to BIM services for facility management.",
    "scope of work": "Architecture, Structure, MEP Modelling; Scan to BIM, As-built data tagging; Asset Information Modelling",
    "image": "null",
    "awards": ""
  },
  {
    "name": "Automatic Train Washing plant",
    "client": "Metro Authority",
    "location": "North India",
    "country": "India",
    "continent": "Asia",
    "lat": "28.6139",
    "lon": "77.209",
    "description": "Specialized industrial facility for metro maintenance.",
    "scope of work": "Architecture, Structure & MEP modeling; Clash Detection and Design Coordination; Quantity Take offs; Design drawing production",
    "image": "null",
    "awards": ""
  },
  {
    "name": "Bridge Modelling, Middle East",
    "client": "Infrastructure Developer",
    "location": "Middle East",
    "country": "Various",
    "continent": "Asia",
    "lat": "25.2048",
    "lon": "55.2708",
    "description": "Structural modeling for major infrastructure crossing.",
    "scope of work": "Structure modeling; Clash Detection and Design Coordination; Design drawing production",
    "image": "null",
    "awards": ""
  },
  {
    "name": "Al Arabi Football Stadium",
    "client": "Sports Authority",
    "location": "Kuwait City",
    "country": "Kuwait",
    "continent": "Asia",
    "lat": "29.3759",
    "lon": "47.9774",
    "description": "Modern sports stadium design and construction.",
    "scope of work": "Architecture Detail Design, Construction Drawings; MEP Design Calculations and Construction Drawings",
    "image": "https://static.wixstatic.com/media/15cdbf_089a0bdd9e9944c2993b49e394b50509~mv2.jpg/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_089a0bdd9e9944c2993b49e394b50509~mv2.jpg",
    "awards": ""
  },
  {
    "name": "Township at Panchkula",
    "client": "Private Developer",
    "location": "Panchkula, Haryana",
    "country": "India",
    "continent": "Asia",
    "lat": "30.6942",
    "lon": "76.8606",
    "description": "Residential township infrastructure and building modeling.",
    "scope of work": "Site contour and infrastructure modelling; Villa and Apartments modelling; Cut and Fill analysis, BIM-based Value Engineering; Quantity Take offs",
    "image": "null",
    "awards": ""
  },
  {
    "name": "Aircraft Hanger refurbishment",
    "client": "Aviation Services",
    "location": "France",
    "country": "France",
    "continent": "Europe",
    "lat": "46.2276",
    "lon": "2.2137",
    "description": "Refurbishment of existing aviation hangar using scan data.",
    "scope of work": "BIM modeling from Scan Data; Importing laser scan point cloud data with BIM; Creating all floor plans, sections and elevations from BIM models",
    "image": "null",
    "awards": ""
  },
  {
    "name": "5 Defries",
    "client": "Graziani + Corazza Architects, Toronto",
    "location": "Toronto",
    "country": "Canada",
    "continent": "North America",
    "lat": "43.651",
    "lon": "-79.347",
    "description": "High-rise residential development in Toronto.",
    "scope of work": "Architecture and structure BIM modeling; Design Development; Construction Drawings",
    "image": "null",
    "awards": ""
  },
  {
    "name": "145 Sheppard East",
    "client": "Graziani + Corazza Architects, Toronto",
    "location": "Toronto",
    "country": "Canada",
    "continent": "North America",
    "lat": "43.7615",
    "lon": "-79.4102",
    "description": "Modern residential project.",
    "scope of work": "Architecture and structure BIM modeling; Design Development; Construction Drawings",
    "image": "null",
    "awards": ""
  },
  {
    "name": "181 Sterling Road",
    "client": "Graziani + Corazza Architects, Toronto",
    "location": "Toronto",
    "country": "Canada",
    "continent": "North America",
    "lat": "43.651",
    "lon": "-79.347",
    "description": "Mixed-use adaptive reuse and new construction.",
    "scope of work": "Architecture and structure BIM modeling; Design Development; Construction Drawings",
    "image": "https://static.wixstatic.com/media/15cdbf_52a17e2cf2274571a6730a7d3a0ba61c~mv2.jpg/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_52a17e2cf2274571a6730a7d3a0ba61c~mv2.jpg",
    "awards": ""
  },
  {
    "name": "Multi-family Residential, Connecticut",
    "client": "Roger Ferris + Partners, Connecticut, USA",
    "location": "Connecticut",
    "country": "USA",
    "continent": "North America",
    "lat": "41.6032",
    "lon": "-73.0877",
    "description": "Residential architecture project.",
    "scope of work": "Architecture and structure BIM modeling; Design Development; Construction Drawings",
    "image": "https://static.wixstatic.com/media/15cdbf_ff0653d783944da99db04f922352f4f8~mv2.png/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_ff0653d783944da99db04f922352f4f8~mv2.png",
    "awards": ""
  },
  {
    "name": "Multi-family Residential, LA",
    "client": "Related California Construction, USA",
    "location": "Los Angeles, CA",
    "country": "USA",
    "continent": "North America",
    "lat": "34.0522",
    "lon": "-118.2437",
    "description": "High-density residential development.",
    "scope of work": "BIM Management; Subcontractor coordination; Slab and Wall penetration drawings",
    "image": "null",
    "awards": ""
  },
  {
    "name": "Permanent Supportive Housing, LA",
    "client": "Related California Construction, USA",
    "location": "Los Angeles, CA",
    "country": "USA",
    "continent": "North America",
    "lat": "34.0522",
    "lon": "-118.2437",
    "description": "Social infrastructure housing project.",
    "scope of work": "BIM Management; Subcontractor coordination; Slab and Wall penetration drawings",
    "image": "null",
    "awards": ""
  },
  {
    "name": "The Dorsey Mixed-use",
    "client": "Beauchamp Construction, Florida, USA",
    "location": "Wynwood, Miami, Florida",
    "country": "USA",
    "continent": "North America",
    "lat": "25.8005",
    "lon": "-80.1993",
    "description": "Mixed-use development in the Wynwood art district.",
    "scope of work": "Virtual Construction ASMEP; Clash Dectection, Coordination; Coordinated Drawing production",
    "image": "null",
    "awards": ""
  },
  {
    "name": "600 Miami World Center",
    "client": "Beauchamp Construction, Florida, USA",
    "location": "Florida",
    "country": "USA",
    "continent": "North America",
    "lat": "27.9944",
    "lon": "-81.7603",
    "description": "Major landmark tower in the Miami World Center development.",
    "scope of work": "Virtual Construction ASMEP; Clash Dectection, Coordination; Coordinated Drawing production",
    "image": "https://static.wixstatic.com/media/15cdbf_04a9fc4404bf45ff9d394cd846701d1f~mv2.png/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_04a9fc4404bf45ff9d394cd846701d1f~mv2.png",
    "awards": ""
  },
  {
    "name": "Canal Park II Office Building",
    "client": "Beauchamp Construction, Florida, USA",
    "location": "Miami, Florida",
    "country": "USA",
    "continent": "North America",
    "lat": "25.7617",
    "lon": "-80.1918",
    "description": "Modern office building infrastructure.",
    "scope of work": "Virtual Construction ASMEP; Clash Dectection, Coordination; Coordinated Drawing production",
    "image": "null",
    "awards": ""
  },
  {
    "name": "2200 Brickell Residential",
    "client": "Ortega Construction, Florida, USA",
    "location": "Miami, Florida",
    "country": "USA",
    "continent": "North America",
    "lat": "25.7617",
    "lon": "-80.1918",
    "description": "Residential high-rise in the Brickell financial district.",
    "scope of work": "Virtual Construction ASMEP; Clash Dectection, Coordination; Coordinated Drawing production",
    "image": "null",
    "awards": ""
  },
  {
    "name": "Medical Emergency Clinic for Atrium Health",
    "client": "Atrium Health",
    "location": "Charlotte, North Carolina",
    "country": "USA",
    "continent": "North America",
    "lat": "35.7596",
    "lon": "-79.0193",
    "description": "Healthcare facility design and construction coordination.",
    "scope of work": "Architecture and structure BIM modeling; Design Development; Construction Drawings",
    "image": "https://static.wixstatic.com/media/15cdbf_b9087194a4cb4182aae66ceb2b078b59~mv2.png/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_b9087194a4cb4182aae66ceb2b078b59~mv2.png",
    "awards": ""
  },
  {
    "name": "MASAR Hotel Complex at Makkah",
    "client": "Meinhardt Dubai",
    "location": "Makkah",
    "country": "Kingdom of Saudi Arabia",
    "continent": "Asia",
    "lat": "21.3891",
    "lon": "39.8579",
    "description": "Hospitality complex part of the Masar destination.",
    "scope of work": "MEP modeling; Clash Detection and Design Coordination; Design Optimization; IFC drawing production",
    "image": "null",
    "awards": ""
  },
  {
    "name": "Innovation Unit Lab",
    "client": "Eastern Mechanical",
    "location": "Ridgefield, Connecticut",
    "country": "USA",
    "continent": "North America",
    "lat": "41.2815",
    "lon": "-73.4982",
    "description": "Research and development laboratory facility.",
    "scope of work": "Updating architecture and structure BIM models; Revision & Model management during construction; Clash detection and design coordination; Bid support for Client's BIM team",
    "image": "null",
    "awards": ""
  },
  {
    "name": "Performing Arts Center",
    "client": "F J Sciame Construction LLC, New York",
    "location": "NY",
    "country": "USA",
    "continent": "North America",
    "lat": "40.7128",
    "lon": "-74.006",
    "description": "World Trade Center Performing Arts Center project.",
    "scope of work": "Updating architecture and structure BIM models; Revision & Model management during construction; Clash detection and design coordination; Bid support for Client's BIM team",
    "image": "https://static.wixstatic.com/media/15cdbf_2e2097a1cb4840518346ff6edd5ca13c~mv2.jpg/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_2e2097a1cb4840518346ff6edd5ca13c~mv2.jpg",
    "awards": ""
  },
  {
    "name": "Bellevue Plaza",
    "client": "GLY Construction, Seattle, USA",
    "location": "WA",
    "country": "USA",
    "continent": "North America",
    "lat": "47.7511",
    "lon": "-120.7401",
    "description": "Commercial office and retail complex.",
    "scope of work": "Model editing; 4D Construction sequence simulation",
    "image": "https://static.wixstatic.com/media/15cdbf_7efa50fe76dc4702b878cb36c72ae446~mv2.jpg/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_7efa50fe76dc4702b878cb36c72ae446~mv2.jpg",
    "awards": ""
  },
  {
    "name": "Major League Baseball Office Interiors",
    "client": "JRM Construction Management, New York",
    "location": "New York",
    "country": "USA",
    "continent": "North America",
    "lat": "40.7128",
    "lon": "-74.006",
    "description": "Office fit-out and coordination for MLB headquarters.",
    "scope of work": "Create structure architecture and MEP BIMs; Compare with Laser Scan data with BIMs/drawings; Complete MEP coordination with Designers & Subs; MEP Shop drawings",
    "image": "null",
    "awards": ""
  },
  {
    "name": "Houston Methodist Hospital at Cypress",
    "client": "McCarthy Construction",
    "location": "Texas",
    "country": "USA",
    "continent": "North America",
    "lat": "29.9717",
    "lon": "-95.6983",
    "description": "Major healthcare expansion with concrete coordination.",
    "scope of work": "Concrete BIM modelling; Coordination with other trades; Concrete Shop drawings with schedules",
    "image": "null",
    "awards": ""
  },
  {
    "name": "Museum of the Future",
    "client": "Dubai Future Foundation",
    "location": "Dubai",
    "country": "UAE",
    "continent": "Asia",
    "lat": "25.2048",
    "lon": "55.2708",
    "description": "Iconic torus-shaped building requiring extremely complex interior coordination.",
    "scope of work": "3D modelling of Interior curved drywall, matching structure and design intent; Shop drawings of interior curved drywall",
    "image": "https://static.wixstatic.com/media/15cdbf_2e45ff8e8db740fda1bc3b945e0a8f9f~mv2.jpg/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_2e45ff8e8db740fda1bc3b945e0a8f9f~mv2.jpg",
    "awards": ""
  },
  {
    "name": "Office Building 4D Construction Sequence",
    "client": "BAM, Germany",
    "location": "Germany",
    "country": "Germany",
    "continent": "Europe",
    "lat": "51.1657",
    "lon": "10.4515",
    "description": "Commercial office project utilizing 4D construction technology.",
    "scope of work": "Architecture & Structure modeling; 4D Construction Sequence Animation; 3D Interior and Extrior Renderings",
    "image": "null",
    "awards": ""
  },
  {
    "name": "Aura Boca Colonnades",
    "client": "Current Builders, Florida",
    "location": "Florida",
    "country": "USA",
    "continent": "North America",
    "lat": "27.9944",
    "lon": "-81.7603",
    "description": "Residential multi-family complex.",
    "scope of work": "Structure, Architecture & MEP Modeling; Clash Detection & Design Coordingation; Model updation; MEP Shop Drawing production",
    "image": "https://static.wixstatic.com/media/15cdbf_ffb6abc228694ccc8dbb2a50bb0e9e65~mv2.jpg/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_ffb6abc228694ccc8dbb2a50bb0e9e65~mv2.jpg",
    "awards": ""
  },
  {
    "name": "LG Headquarters",
    "client": "EDA Contractors, Philadelphia",
    "location": "New Jersey",
    "country": "USA",
    "continent": "North America",
    "lat": "40.0583",
    "lon": "-74.4057",
    "description": "Corporate headquarters development.",
    "scope of work": "BIM vs as-built Scan Validation; Shop drawing change identification; Shop drawings modifications",
    "image": "https://static.wixstatic.com/media/15cdbf_99d481e74679483d888471e5ddec6be9~mv2.png/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_99d481e74679483d888471e5ddec6be9~mv2.png",
    "awards": ""
  },
  {
    "name": "Cruise Terminal 25 (T25)",
    "client": "Moss Construction & Rightway Plumbing",
    "location": "Miami",
    "country": "USA",
    "continent": "North America",
    "lat": "25.7617",
    "lon": "-80.1918",
    "description": "Detailed MEP coordination for terminal infrastructure.",
    "scope of work": "Complete LOD 400 MEP Modeling; Clash Detection and Design Coordination; Design Change Management; Plumbing Shop Drawings",
    "image": "https://static.wixstatic.com/media/15cdbf_e4647ee546974b5e81443bb7f2c74533~mv2.png/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_e4647ee546974b5e81443bb7f2c74533~mv2.png",
    "awards": ""
  },
  {
    "name": "Santa Clara Gateway Office Complex",
    "client": "DPR Construction, Redwood City",
    "location": "California, USA",
    "country": "USA",
    "continent": "North America",
    "lat": "37.3541",
    "lon": "-121.9552",
    "description": "Tech-focused office complex.",
    "scope of work": "Creation of architecture and structure BIMs; Construction sequence simulation using Navisworks; 3D visualization; Bid support for contracts team",
    "image": "null",
    "awards": ""
  },
  {
    "name": "Apple Store",
    "client": "DPR Construction, Redwood City",
    "location": "California, USA",
    "country": "USA",
    "continent": "North America",
    "lat": "37.0902",
    "lon": "-95.7129",
    "description": "Retail development with complex constructability requirements.",
    "scope of work": "Virtual Construction off architecture and structure; Constructability analysis; Clash detection and design coordination; Visualization support to inhouse BIM team",
    "image": "https://static.wixstatic.com/media/15cdbf_6c21621c9fa2414da547b6a393d304e7~mv2.png/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_6c21621c9fa2414da547b6a393d304e7~mv2.png",
    "awards": ""
  },
  {
    "name": "Climate Pledge Arena Stadium",
    "client": "Mortenson Construction and Firstline Systems",
    "location": "WA",
    "country": "USA",
    "continent": "North America",
    "lat": "47.7511",
    "lon": "-120.7401",
    "description": "Stadium renovation with detailed interior systems.",
    "scope of work": "Prepare partition system BIM model",
    "image": "https://static.wixstatic.com/media/15cdbf_f723522d3cc944c69a03561c9c752783~mv2.jpg/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_f723522d3cc944c69a03561c9c752783~mv2.jpg",
    "awards": ""
  },
  {
    "name": "Midlands Garden Care Community Apartments",
    "client": "Unknown",
    "location": "Ontario",
    "country": "Canada",
    "continent": "North America",
    "lat": "51.2538",
    "lon": "-85.3232",
    "description": "Residential care community project.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_632cfda5eb72497d95ba559c0e1f78f7~mv2.jpg/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_632cfda5eb72497d95ba559c0e1f78f7~mv2.jpg",
    "awards": ""
  },
  {
    "name": "Guldhar Metro Station",
    "client": "Metro Authority",
    "location": "Ghaziabad",
    "country": "India",
    "continent": "Asia",
    "lat": "28.6692",
    "lon": "77.4538",
    "description": "Regional Rapid Transit System (RRTS) station.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_746c456b0e0b45f2b26c7ac2665c497e~mv2.jpg/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_746c456b0e0b45f2b26c7ac2665c497e~mv2.jpg",
    "awards": ""
  },
  {
    "name": "420 Mendocino",
    "client": "Unknown",
    "location": "CA",
    "country": "USA",
    "continent": "North America",
    "lat": "36.7783",
    "lon": "-119.4179",
    "description": "Commercial/Residential development.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_153a2b5b079440c8b9896aba9860cd5c~mv2.jpg/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_153a2b5b079440c8b9896aba9860cd5c~mv2.jpg",
    "awards": ""
  },
  {
    "name": "Plano ISD Senior High School",
    "client": "School District",
    "location": "Texas",
    "country": "USA",
    "continent": "North America",
    "lat": "31.9686",
    "lon": "-99.9018",
    "description": "Educational facility expansion.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_1300a5239bf941c7bcba11795929d5e0~mv2.jpg/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_1300a5239bf941c7bcba11795929d5e0~mv2.jpg",
    "awards": ""
  },
  {
    "name": "Godrej Commercial Tower",
    "client": "Godrej Fund Management",
    "location": "Gurugram",
    "country": "India",
    "continent": "Asia",
    "lat": "28.4595",
    "lon": "77.0266",
    "description": "Modern office building.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_fe7f7eb0b5fc44a4996557e5f696a76c~mv2.jpg/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_fe7f7eb0b5fc44a4996557e5f696a76c~mv2.jpg",
    "awards": ""
  },
  {
    "name": "Medical Office Building",
    "client": "Healthcare Developer",
    "location": "Ontario",
    "country": "Canada",
    "continent": "North America",
    "lat": "51.2538",
    "lon": "-85.3232",
    "description": "Healthcare administrative and clinic space.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_972f652576bc44c1a85ba8fbb6d03f32~mv2.jpg/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_972f652576bc44c1a85ba8fbb6d03f32~mv2.jpg",
    "awards": ""
  },
  {
    "name": "Costco, Crick",
    "client": "Costco Wholesale",
    "location": "Birmingham",
    "country": "UK",
    "continent": "Europe",
    "lat": "52.4862",
    "lon": "-1.8904",
    "description": "Large scale retail warehouse project.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_6f91e9b7e66d4b489c45cccfedcf3124~mv2.jpg/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_6f91e9b7e66d4b489c45cccfedcf3124~mv2.jpg",
    "awards": ""
  },
  {
    "name": "Trinity High School",
    "client": "School Board",
    "location": "Hawaii",
    "country": "USA",
    "continent": "North America",
    "lat": "19.8968",
    "lon": "-155.5828",
    "description": "Educational facility development.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_2a6f3b400a25471cb9e179ccf29d9677~mv2.jpg/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_2a6f3b400a25471cb9e179ccf29d9677~mv2.jpg",
    "awards": ""
  },
  {
    "name": "Hyatt Place",
    "client": "Hyatt",
    "location": "Delhi",
    "country": "India",
    "continent": "Asia",
    "lat": "28.6139",
    "lon": "77.209",
    "description": "Hospitality development in the capital region.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_44e4c4f1964947bb88a8f27b0d87fb09~mv2.png/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_44e4c4f1964947bb88a8f27b0d87fb09~mv2.png",
    "awards": ""
  },
  {
    "name": "Jake's Hotel and Casino",
    "client": "Entertainment Group",
    "location": "NY",
    "country": "USA",
    "continent": "North America",
    "lat": "40.7128",
    "lon": "-74.006",
    "description": "Gaming and hospitality project.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_c97f5240e5824dcdb8a589e773af4867~mv2.jpg/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_c97f5240e5824dcdb8a589e773af4867~mv2.jpg",
    "awards": ""
  },
  {
    "name": "Mixed Use Development",
    "client": "Developer",
    "location": "Florida",
    "country": "USA",
    "continent": "North America",
    "lat": "27.9944",
    "lon": "-81.7603",
    "description": "Retail, office, and residential development.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_bacb2c81941947139e53bafbfd5009d1~mv2.jpg/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_bacb2c81941947139e53bafbfd5009d1~mv2.jpg",
    "awards": ""
  },
  {
    "name": "Discount Tyre",
    "client": "Discount Tire Co.",
    "location": "USA",
    "country": "USA",
    "continent": "North America",
    "lat": "37.0902",
    "lon": "-95.7129",
    "description": "Retail rollout project.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_ad3d1b29773547bf9448d65e397d3e52~mv2.jpg/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_ad3d1b29773547bf9448d65e397d3e52~mv2.jpg",
    "awards": ""
  },
  {
    "name": "Al Sufouh Tower",
    "client": "Unknown",
    "location": "Dubai",
    "country": "UAE",
    "continent": "Asia",
    "lat": "25.2048",
    "lon": "55.2708",
    "description": "High-rise residential tower.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_3d4eb32917e54ff6adc879ba6a5951f2~mv2.png/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_3d4eb32917e54ff6adc879ba6a5951f2~mv2.png",
    "awards": ""
  },
  {
    "name": "8188 Yonge Street",
    "client": "Residential Developer",
    "location": "Thornhill",
    "country": "Canada",
    "continent": "North America",
    "lat": "43.8163",
    "lon": "-79.4287",
    "description": "Luxury residential tower.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_030fdd84ebdc4b8f84c764644c11c1dc~mv2.jpg/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_030fdd84ebdc4b8f84c764644c11c1dc~mv2.jpg",
    "awards": ""
  },
  {
    "name": "Victoria's Secret",
    "client": "L Brands",
    "location": "USA",
    "country": "USA",
    "continent": "North America",
    "lat": "37.0902",
    "lon": "-95.7129",
    "description": "Retail store rollout and fit-outs.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_d201ba54f1f6474d9dc2e9a9a2d40c51~mv2.png/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_d201ba54f1f6474d9dc2e9a9a2d40c51~mv2.png",
    "awards": ""
  },
  {
    "name": "Renaissance Plano Legacy West",
    "client": "Marriott Renaissance",
    "location": "Texas",
    "country": "USA",
    "continent": "North America",
    "lat": "31.9686",
    "lon": "-99.9018",
    "description": "Luxury hotel development.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_9c6ec31dbf0e47f38cefa63aeb0ffba4~mv2.jpg/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_9c6ec31dbf0e47f38cefa63aeb0ffba4~mv2.jpg",
    "awards": ""
  },
  {
    "name": "Rua Al Madinah Marriott",
    "client": "Rua Al Madinah Holding",
    "location": "Madinah",
    "country": "Kingdom of Saudi Arabia",
    "continent": "Asia",
    "lat": "24.5247",
    "lon": "39.5692",
    "description": "Hospitality project in the holy city of Madinah.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_a7ccbf67d1b446f39a5b9faf3d414dde~mv2.jpg/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_a7ccbf67d1b446f39a5b9faf3d414dde~mv2.jpg",
    "awards": ""
  },
  {
    "name": "Paras One",
    "client": "Paras Buildtech",
    "location": "Greater Noida",
    "country": "India",
    "continent": "Asia",
    "lat": "28.4744",
    "lon": "77.504",
    "description": "Commercial development.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_c74eaf410799489faca3c3a659e05e5f~mv2.png/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_c74eaf410799489faca3c3a659e05e5f~mv2.png",
    "awards": ""
  },
  {
    "name": "Long Term Care Hospital",
    "client": "Healthcare Provider",
    "location": "Riyadh",
    "country": "Kingdom of Saudi Arabia",
    "continent": "Asia",
    "lat": "24.7136",
    "lon": "46.6753",
    "description": "Specialized long-term medical facility.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_d44eee0e5b5e45678e45acb38c6448d0~mv2.png/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_d44eee0e5b5e45678e45acb38c6448d0~mv2.png",
    "awards": ""
  },
  {
    "name": "Reem Hills North Island Villas",
    "client": "Q Properties",
    "location": "Abu Dhabi",
    "country": "UAE",
    "continent": "Asia",
    "lat": "24.4539",
    "lon": "54.3773",
    "description": "Luxury villa development on Reem Island.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_26a7041459ec4c7ebce058477c0a7aca~mv2.jpg/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_26a7041459ec4c7ebce058477c0a7aca~mv2.jpg",
    "awards": ""
  },
  {
    "name": "JM Campus",
    "client": "Unknown",
    "location": "USA",
    "country": "USA",
    "continent": "North America",
    "lat": "37.0902",
    "lon": "-95.7129",
    "description": "Educational or corporate campus development.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_76e524f4644546babd18c662d0ba9535~mv2.png/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_76e524f4644546babd18c662d0ba9535~mv2.png",
    "awards": ""
  },
  {
    "name": "Jumeirah Village Triangle",
    "client": "Nakheel",
    "location": "Dubai",
    "country": "UAE",
    "continent": "Asia",
    "lat": "25.2048",
    "lon": "55.2708",
    "description": "Residential community development.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_9ad1bf293e474f56b998de745dc884e0~mv2.jpg/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_9ad1bf293e474f56b998de745dc884e0~mv2.jpg",
    "awards": ""
  },
  {
    "name": "Iconic Mixed Use Development",
    "client": "Developer",
    "location": "NYC",
    "country": "USA",
    "continent": "North America",
    "lat": "40.7128",
    "lon": "-74.006",
    "description": "Landmark high-rise project.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_980aaa947fdc4996ad7ecebd92c9e350~mv2.jpg/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_980aaa947fdc4996ad7ecebd92c9e350~mv2.jpg",
    "awards": ""
  },
  {
    "name": "Boro Tower",
    "client": "The Boro",
    "location": "VA",
    "country": "USA",
    "continent": "North America",
    "lat": "37.4316",
    "lon": "-78.6569",
    "description": "Grade-A office tower.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_6081d8918fb44f259df0c3aed12d3f02~mv2.jpg/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_6081d8918fb44f259df0c3aed12d3f02~mv2.jpg",
    "awards": ""
  },
  {
    "name": "740 Eighth Avenue",
    "client": "Developer",
    "location": "MA",
    "country": "USA",
    "continent": "North America",
    "lat": "42.4072",
    "lon": "-71.3824",
    "description": "Commercial development.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_69a0bb66f6b1435cb17281f4d12dc2a7~mv2.jpg/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_69a0bb66f6b1435cb17281f4d12dc2a7~mv2.jpg",
    "awards": ""
  },
  {
    "name": "Vatika Tranquil Heights",
    "client": "Vatika Group",
    "location": "Gurgaon",
    "country": "India",
    "continent": "Asia",
    "lat": "28.4595",
    "lon": "77.0266",
    "description": "Luxury residential development.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_f284b9238cd146c0a313b39de01c1660~mv2.png/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_f284b9238cd146c0a313b39de01c1660~mv2.png",
    "awards": ""
  },
  {
    "name": "Burjuman Mall",
    "client": "Al Ghurair Group",
    "location": "Dubai",
    "country": "UAE",
    "continent": "Asia",
    "lat": "25.2048",
    "lon": "55.2708",
    "description": "Retail mall redevelopment.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_c2b4dd71ecd64d379262162c9f8df2ee~mv2.jpg/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_c2b4dd71ecd64d379262162c9f8df2ee~mv2.jpg",
    "awards": ""
  },
  {
    "name": "Save On Foods",
    "client": "Pattison Food Group",
    "location": "Prince George",
    "country": "Canada",
    "continent": "North America",
    "lat": "53.9171",
    "lon": "-122.7497",
    "description": "Grocery store development.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_eb9b82cec7244d41bd6947f06a368103~mv2.jpg/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_eb9b82cec7244d41bd6947f06a368103~mv2.jpg",
    "awards": ""
  },
  {
    "name": "RRTS Sahibabad Metro Station",
    "client": "NCRTC",
    "location": "Ghaziabad",
    "country": "India",
    "continent": "Asia",
    "lat": "28.6692",
    "lon": "77.4538",
    "description": "Rapid transit station development.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_760cfb89050e4ec3a067e5cf6138aba7~mv2.png/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_760cfb89050e4ec3a067e5cf6138aba7~mv2.png",
    "awards": ""
  },
  {
    "name": "Chamberlain House",
    "client": "Unknown",
    "location": "Birmingham",
    "country": "UK",
    "continent": "Europe",
    "lat": "52.4862",
    "lon": "-1.8904",
    "description": "Historic or residential development.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_d5a2a5e55f434e8ab91d1ee5a65dc7cc~mv2.jpg/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_d5a2a5e55f434e8ab91d1ee5a65dc7cc~mv2.jpg",
    "awards": ""
  },
  {
    "name": "Misk City Kindergarten School",
    "client": "Misk City",
    "location": "Riyadh",
    "country": "Kingdom of Saudi Arabia",
    "continent": "Asia",
    "lat": "24.7136",
    "lon": "46.6753",
    "description": "Educational facility within Misk City.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_010254c9b832480a9ab94ceff83fc1c2~mv2.jpg/v1/fill/w_320,h_308,q_90,enc_avif,quality_auto/15cdbf_010254c9b832480a9ab94ceff83fc1c2~mv2.jpg",
    "awards": ""
  },
  {
    "name": "Ely Gateway",
    "client": "Unknown",
    "location": "Cambridgeshire",
    "country": "UK",
    "continent": "Europe",
    "lat": "52.399",
    "lon": "0.2621",
    "description": "Mixed-use development.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_459b155a5b004eb08235d7883057f352~mv2.jpg/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_459b155a5b004eb08235d7883057f352~mv2.jpg",
    "awards": ""
  },
  {
    "name": "Dior",
    "client": "Christian Dior",
    "location": "USA",
    "country": "USA",
    "continent": "North America",
    "lat": "37.0902",
    "lon": "-95.7129",
    "description": "Luxury retail store development.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_362ae66d097943d2a20ca17b98c771f0~mv2.png/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_362ae66d097943d2a20ca17b98c771f0~mv2.png",
    "awards": ""
  },
  {
    "name": "Fred Hutch Building",
    "client": "Fred Hutch Cancer Center",
    "location": "Seattle",
    "country": "USA",
    "continent": "North America",
    "lat": "47.6062",
    "lon": "-122.3321",
    "description": "Scientific research facility.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_a4cfdb2ee46748a4b4d838450600b215~mv2.jpg/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_a4cfdb2ee46748a4b4d838450600b215~mv2.jpg",
    "awards": ""
  },
  {
    "name": "Park Signet",
    "client": "Lodha Developers",
    "location": "Mumbai",
    "country": "India",
    "continent": "Asia",
    "lat": "19.076",
    "lon": "72.8777",
    "description": "Hospitality or residential development.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_d22bc51c35dc40d1baaf23ac4fbbbd7b~mv2.png/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_d22bc51c35dc40d1baaf23ac4fbbbd7b~mv2.png",
    "awards": ""
  },
  {
    "name": "Starbucks",
    "client": "Starbucks Corporation",
    "location": "USA",
    "country": "USA",
    "continent": "North America",
    "lat": "37.0902",
    "lon": "-95.7129",
    "description": "Retail rollout coordination.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_de69975a0d894c9bafd775466f782d2c~mv2.png/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_de69975a0d894c9bafd775466f782d2c~mv2.png",
    "awards": ""
  },
  {
    "name": "Redondo Heights",
    "client": "Unknown",
    "location": "WA",
    "country": "USA",
    "continent": "North America",
    "lat": "47.7511",
    "lon": "-120.7401",
    "description": "Residential project.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_4809c31f9a824aaf98507c87bfa19365~mv2.jpg/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_4809c31f9a824aaf98507c87bfa19365~mv2.jpg",
    "awards": ""
  },
  {
    "name": "270 Park Avenue",
    "client": "JPMorgan Chase",
    "location": "NY",
    "country": "USA",
    "continent": "North America",
    "lat": "40.7128",
    "lon": "-74.006",
    "description": "New headquarters for JPMorgan Chase.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_1fe233238fed46dda25143ec09b15832~mv2.jpg/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_1fe233238fed46dda25143ec09b15832~mv2.jpg",
    "awards": ""
  },
  {
    "name": "Spectrum Center",
    "client": "Unknown",
    "location": "Gurgaon",
    "country": "India",
    "continent": "Asia",
    "lat": "28.4595",
    "lon": "77.0266",
    "description": "Commercial retail and office center.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_4f5420e6f64a460e9a85907ed57dac0b~mv2.png/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_4f5420e6f64a460e9a85907ed57dac0b~mv2.png",
    "awards": ""
  },
  {
    "name": "Wirral Waters",
    "client": "Peel L&P",
    "location": "England",
    "country": "UK",
    "continent": "Europe",
    "lat": "52.3555",
    "lon": "-1.1743",
    "description": "Major waterfront regeneration project.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_724b5607b4014ae9ae6bd4569ba87419~mv2.jpg/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_724b5607b4014ae9ae6bd4569ba87419~mv2.jpg",
    "awards": ""
  },
  {
    "name": "Mediana Hotel Interior",
    "client": "Hospitality Group",
    "location": "Saudi Arabia",
    "country": "Saudi Arabia",
    "continent": "Asia",
    "lat": "23.8859",
    "lon": "45.0792",
    "description": "Interior BIM coordination for hotel project.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_89d69772b3074e31b25facfd3b6377b3~mv2.png/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_89d69772b3074e31b25facfd3b6377b3~mv2.png",
    "awards": ""
  },
  {
    "name": "Dubai Design District d3",
    "client": "TECOM Group",
    "location": "UAE",
    "country": "UAE",
    "continent": "Asia",
    "lat": "23.4241",
    "lon": "53.8478",
    "description": "Design-focused commercial district.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_6b1d1649191b494d9d40ef5edfdfddb5~mv2.png/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_6b1d1649191b494d9d40ef5edfdfddb5~mv2.png",
    "awards": ""
  },
  {
    "name": "School in Hawaii",
    "client": "Educational Board",
    "location": "USA",
    "country": "USA",
    "continent": "North America",
    "lat": "37.0902",
    "lon": "-95.7129",
    "description": "K-12 educational facility.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_9454863c4ce1448a946127ba73363fe5~mv2.jpg/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_9454863c4ce1448a946127ba73363fe5~mv2.jpg",
    "awards": ""
  },
  {
    "name": "ATS Pragya",
    "client": "ATS Infrastructure",
    "location": "Gandhinagar",
    "country": "India",
    "continent": "Asia",
    "lat": "23.2156",
    "lon": "72.6369",
    "description": "Commercial development in GIFT City.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_6958f56984bc4f099316a95de5e06d16~mv2.png/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_6958f56984bc4f099316a95de5e06d16~mv2.png",
    "awards": ""
  },
  {
    "name": "Town Square",
    "client": "Vatika Group",
    "location": "Gurgaon",
    "country": "India",
    "continent": "Asia",
    "lat": "28.4595",
    "lon": "77.0266",
    "description": "Integrated commercial and retail township.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_1adc2318949c4fc8b89e376159818361~mv2.png/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_1adc2318949c4fc8b89e376159818361~mv2.png",
    "awards": ""
  },
  {
    "name": "Ace 153 Sector 153",
    "client": "Ace Group",
    "location": "Noida",
    "country": "India",
    "continent": "Asia",
    "lat": "28.5355",
    "lon": "77.391",
    "description": "Premium commercial development.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_3ce825fba3054aada4d87b6730e6afb3~mv2.jpg/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_3ce825fba3054aada4d87b6730e6afb3~mv2.jpg",
    "awards": ""
  },
  {
    "name": "Mixed Use Development",
    "client": "Developer",
    "location": "WA",
    "country": "USA",
    "continent": "North America",
    "lat": "47.7511",
    "lon": "-120.7401",
    "description": "Multi-use commercial project.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_7a647e280a514e12a6bacd3dcd3b20d9~mv2.png/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_7a647e280a514e12a6bacd3dcd3b20d9~mv2.png",
    "awards": ""
  },
  {
    "name": "Police Hospital",
    "client": "Ministry of Interior",
    "location": "Qatar",
    "country": "Qatar",
    "continent": "Asia",
    "lat": "25.3548",
    "lon": "51.1839",
    "description": "Healthcare facility for security forces.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_6dec227bc72c4c6aad7d9b6957d06f78~mv2.jpg/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_6dec227bc72c4c6aad7d9b6957d06f78~mv2.jpg",
    "awards": ""
  },
  {
    "name": "McKinney Boyd High School",
    "client": "McKinney ISD",
    "location": "Texas",
    "country": "USA",
    "continent": "North America",
    "lat": "31.9686",
    "lon": "-99.9018",
    "description": "Educational facility improvement.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_2491d50985a34a21a3c0f471f4c7fb4a~mv2.jpg/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_2491d50985a34a21a3c0f471f4c7fb4a~mv2.jpg",
    "awards": ""
  },
  {
    "name": "Hyatt Place",
    "client": "Hyatt",
    "location": "Illinois",
    "country": "USA",
    "continent": "North America",
    "lat": "40",
    "lon": "-89",
    "description": "Hospitality development in the Midwest.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_db38f1a79562473fa0596310ed12c412~mv2.png/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_db38f1a79562473fa0596310ed12c412~mv2.png",
    "awards": ""
  },
  {
    "name": "Palace Project",
    "client": "Royal Family",
    "location": "Doha",
    "country": "Qatar",
    "continent": "Asia",
    "lat": "25.2854",
    "lon": "51.531",
    "description": "High-end residential palace project.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_9e7a62df6e9e487382aa9fc4ff42619b~mv2.jpg/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_9e7a62df6e9e487382aa9fc4ff42619b~mv2.jpg",
    "awards": ""
  },
  {
    "name": "T3 Bayside",
    "client": "Hines",
    "location": "Toronto",
    "country": "Canada",
    "continent": "North America",
    "lat": "43.651",
    "lon": "-79.347",
    "description": "Mass-timber office building.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_c80324f70bc04992af559e99f76d3160~mv2.jpg/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_c80324f70bc04992af559e99f76d3160~mv2.jpg",
    "awards": ""
  },
  {
    "name": "Misk City",
    "client": "Misk Foundation",
    "location": "Riyadh",
    "country": "Kingdom of Saudi Arabia",
    "continent": "Asia",
    "lat": "24.7136",
    "lon": "46.6753",
    "description": "Sustainable city development focusing on education and innovation.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_55e06a83cb4e42ec9e10311d6631f0de~mv2.jpg/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_55e06a83cb4e42ec9e10311d6631f0de~mv2.jpg",
    "awards": ""
  },
  {
    "name": "Ritz-Carlton",
    "client": "Marriott International",
    "location": "Florida",
    "country": "USA",
    "continent": "North America",
    "lat": "27.9944",
    "lon": "-81.7603",
    "description": "Luxury hotel development.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_6045ead050cf4e73af0974d52fa9f87d~mv2.jpg/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_6045ead050cf4e73af0974d52fa9f87d~mv2.jpg",
    "awards": ""
  },
  {
    "name": "Lavazza Cafe",
    "client": "Lavazza",
    "location": "USA",
    "country": "USA",
    "continent": "North America",
    "lat": "37.0902",
    "lon": "-95.7129",
    "description": "Commercial fit-out projects.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_c456405c3fcf4d8daae0487c7207cae6~mv2.jpg/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_c456405c3fcf4d8daae0487c7207cae6~mv2.jpg",
    "awards": ""
  },
  {
    "name": "250 City Road Phase 3",
    "client": "Berkeley Group",
    "location": "London",
    "country": "UK",
    "continent": "Europe",
    "lat": "51.5074",
    "lon": "-0.1278",
    "description": "High-rise residential and commercial development.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_8dec42c7e2f44c0098f1d2946ec0d2ca~mv2.jpg/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_8dec42c7e2f44c0098f1d2946ec0d2ca~mv2.jpg",
    "awards": ""
  },
  {
    "name": "New York Blood Center",
    "client": "NYBC",
    "location": "NY",
    "country": "USA",
    "continent": "North America",
    "lat": "40.7128",
    "lon": "-74.006",
    "description": "Laboratory and healthcare administrative center.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_aa5ec414851746a58f5e8f5b593f5af7~mv2.jpg/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_aa5ec414851746a58f5e8f5b593f5af7~mv2.jpg",
    "awards": ""
  },
  {
    "name": "Kings College Hospital",
    "client": "ASHMORE",
    "location": "Dubai",
    "country": "UAE",
    "continent": "Asia",
    "lat": "25.2048",
    "lon": "55.2708",
    "description": "State-of-the-art healthcare facility.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_29e94dbffd074d61b009d450fe7adaac~mv2.jpg/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_29e94dbffd074d61b009d450fe7adaac~mv2.jpg",
    "awards": ""
  },
  {
    "name": "Tauras",
    "client": "Unknown",
    "location": "Bangalore",
    "country": "India",
    "continent": "Asia",
    "lat": "12.9716",
    "lon": "77.5946",
    "description": "Commercial building project.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_f44a3948bee1467e95e90710fdd5ad76~mv2.jpg/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_f44a3948bee1467e95e90710fdd5ad76~mv2.jpg",
    "awards": ""
  },
  {
    "name": "Ailsa Wharf Phase 1",
    "client": "Developer",
    "location": "London",
    "country": "UK",
    "continent": "Europe",
    "lat": "51.5074",
    "lon": "-0.1278",
    "description": "Residential development in the East End.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_ba9062bae92f45778ec0fa59f136c869~mv2.jpg/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_ba9062bae92f45778ec0fa59f136c869~mv2.jpg",
    "awards": ""
  },
  {
    "name": "Crate & Barrel",
    "client": "Crate & Barrel Holdings",
    "location": "USA",
    "country": "USA",
    "continent": "North America",
    "lat": "37.0902",
    "lon": "-95.7129",
    "description": "Retail rollout coordination.",
    "scope of work": "-",
    "image": "https://static.wixstatic.com/media/15cdbf_31d2f546f2684e3ba5d9a65ee9484177~mv2.png/v1/fill/w_320,h_320,q_90,enc_avif,quality_auto/15cdbf_31d2f546f2684e3ba5d9a65ee9484177~mv2.png",
    "awards": ""
  },
  {
    "name": "Godrej Ananda Hills",
    "client": "Godrej Properties Ltd.",
    "location": "Bengaluru",
    "country": "India",
    "continent": "Asia",
    "lat": "12.9716",
    "lon": "77.5946",
    "description": "Residential development project.",
    "scope of work": "",
    "image": "null",
    "awards": ""
  },
  {
    "name": "Gurgaon Commercial",
    "client": "Godrej Fund Mgmt",
    "location": "Gurgaon",
    "country": "India",
    "continent": "Asia",
    "lat": "28.4595",
    "lon": "77.0266",
    "description": "Commercial office development project.",
    "scope of work": "",
    "image": "null",
    "awards": ""
  },
  {
    "name": "Taurus-2 Office Tower",
    "client": "Bagmane Developers",
    "location": "Bengaluru",
    "country": "India",
    "continent": "Asia",
    "lat": "12.9716",
    "lon": "77.5946",
    "description": "Commercial office tower project.",
    "scope of work": "",
    "image": "null",
    "awards": ""
  },
  {
    "name": "Hospital, Academic Bldgs.",
    "client": "Girdhari Lal Construction",
    "location": "Karnal",
    "country": "India",
    "continent": "Asia",
    "lat": "29.6857",
    "lon": "76.9905",
    "description": "Healthcare and academic infrastructure project.",
    "scope of work": "",
    "image": "null",
    "awards": ""
  },
  {
    "name": "Metro Stations (4 nos.)",
    "client": "SAM India",
    "location": "Meerut",
    "country": "India",
    "continent": "Asia",
    "lat": "28.9845",
    "lon": "77.7064",
    "description": "Metro station infrastructure project.",
    "scope of work": "Architecture, Structure & MEP modeling; Clash Detection and Design Coordination; Quantity Take offs; Design drawing production",
    "image": "null",
    "awards": ""
  },
  {
    "name": "Metro Infrastructure BIM",
    "client": "Bombardier",
    "location": "Multiple",
    "country": "India",
    "continent": "Asia",
    "lat": "20.5937",
    "lon": "78.9629",
    "description": "BIM services for metro infrastructure.",
    "scope of work": "",
    "image": "null",
    "awards": ""
  },
  {
    "name": "NOIDA International Airport",
    "client": "STUP",
    "location": "NOIDA",
    "country": "India",
    "continent": "Asia",
    "lat": "28.5355",
    "lon": "77.391",
    "description": "Airport infrastructure development.",
    "scope of work": "",
    "image": "null",
    "awards": ""
  },
  {
    "name": "Convention Center",
    "client": "ARCOP",
    "location": "Delhi",
    "country": "India",
    "continent": "Asia",
    "lat": "28.6139",
    "lon": "77.209",
    "description": "Convention and exhibition infrastructure project.",
    "scope of work": "",
    "image": "null",
    "awards": ""
  },
  {
    "name": "IREO Residential, Sec 59",
    "client": "IREO",
    "location": "Gurgaon",
    "country": "India",
    "continent": "Asia",
    "lat": "28.42",
    "lon": "77.1",
    "description": "Residential apartment development.",
    "scope of work": "",
    "image": "null",
    "awards": ""
  },
  {
    "name": "IREO Sales Gallery",
    "client": "IREO",
    "location": "Gurgaon",
    "country": "India",
    "continent": "Asia",
    "lat": "28.4595",
    "lon": "77.0266",
    "description": "Commercial sales gallery project.",
    "scope of work": "",
    "image": "null",
    "awards": ""
  },
  {
    "name": "Residence at Shanti Niketan",
    "client": "Trident Group",
    "location": "Delhi",
    "country": "India",
    "continent": "Asia",
    "lat": "28.5823",
    "lon": "77.1686",
    "description": "Luxury residential project.",
    "scope of work": "",
    "image": "null",
    "awards": ""
  },
  {
    "name": "Residence at Chandigarh",
    "client": "Trident Group",
    "location": "Chandigarh",
    "country": "India",
    "continent": "Asia",
    "lat": "30.7333",
    "lon": "76.7794",
    "description": "Residential development project.",
    "scope of work": "",
    "image": "null",
    "awards": ""
  },
  {
    "name": "NTPC Tower",
    "client": "Raj Rewal Associates",
    "location": "NOIDA",
    "country": "India",
    "continent": "Asia",
    "lat": "28.5355",
    "lon": "77.391",
    "description": "Commercial office tower project.",
    "scope of work": "",
    "image": "null",
    "awards": ""
  },
  {
    "name": "Mixed Use development",
    "client": "Burman GSC Developers",
    "location": "Sector 82A, Gurgaon",
    "country": "India",
    "continent": "Asia",
    "lat": "28.385",
    "lon": "76.969",
    "description": "Mixed-use development project.",
    "scope of work": "",
    "image": "null",
    "awards": ""
  },
  {
    "name": "Warehouses (3 no.)",
    "client": "AssetMax / SafeExpress",
    "location": "Ranjangaon, Kalamboli, Ludhiana",
    "country": "India",
    "continent": "Asia",
    "lat": "20.75",
    "lon": "75.7139",
    "description": "Industrial warehouse developments.",
    "scope of work": "",
    "image": "null",
    "awards": ""
  },
  {
    "name": "Jasola Metro - Retail / mall",
    "client": "Pacific Developers",
    "location": "Delhi",
    "country": "India",
    "continent": "Asia",
    "lat": "28.545",
    "lon": "77.291",
    "description": "Commercial retail and mall development.",
    "scope of work": "",
    "image": "null",
    "awards": ""
  },
  {
    "name": "Precinct 2 & 3 (Phase1) Mixed use",
    "client": "Bhartiya City Developer",
    "location": "Germany",
    "country": "Germany",
    "continent": "Europe",
    "lat": "51.1657",
    "lon": "10.4515",
    "description": "Mixed-use urban development project.",
    "scope of work": "",
    "image": "null",
    "awards": ""
  },
  {
    "name": "Hotel (Eclipse Building)",
    "client": "BAM, Germany",
    "location": "Germany",
    "country": "Germany",
    "continent": "Europe",
    "lat": "51.1657",
    "lon": "10.4515",
    "description": "Hospitality development project.",
    "scope of work": "",
    "image": "null",
    "awards": ""
  },
  {
    "name": "office building (BC Zalandog)",
    "client": "BAM, Germany",
    "location": "Germany",
    "country": "Germany",
    "continent": "Europe",
    "lat": "51.1657",
    "lon": "10.4515",
    "description": "Commercial office development.",
    "scope of work": "",
    "image": "null",
    "awards": ""
  },
  {
    "name": "Office Lab Campus",
    "client": "BAM, Germany",
    "location": "Germany",
    "country": "Germany",
    "continent": "Europe",
    "lat": "51.1657",
    "lon": "10.4515",
    "description": "Office and laboratory campus project.",
    "scope of work": "",
    "image": "null",
    "awards": ""
  },
  {
    "name": "Ballroom Expansion",
    "client": "International Client",
    "location": "Florida, USA",
    "country": "USA",
    "continent": "North America",
    "lat": "27.6648",
    "lon": "-81.5158",
    "description": "Commercial ballroom expansion project.",
    "scope of work": "",
    "image": "null",
    "awards": ""
  },
  {
    "name": "Villa Development",
    "client": "International Client",
    "location": "Dubai, UAE",
    "country": "UAE",
    "continent": "Asia",
    "lat": "25.2048",
    "lon": "55.2708",
    "description": "Luxury villa residential development.",
    "scope of work": "",
    "image": "null",
    "awards": ""
  },
  {
    "name": "Commercial Development with 3 Office Buildings",
    "client": "International Client",
    "location": "Santa Clara, USA",
    "country": "USA",
    "continent": "North America",
    "lat": "37.3541",
    "lon": "-121.9552",
    "description": "Commercial office campus development.",
    "scope of work": "",
    "image": "null",
    "awards": "Awarded for Commercial Excellence (Sep-11)"
  },
  {
    "name": "Residential development",
    "client": "International Client",
    "location": "Maryland, USA",
    "country": "USA",
    "continent": "North America",
    "lat": "39.0458",
    "lon": "-76.6413",
    "description": "Residential apartment development project.",
    "scope of work": "",
    "image": "null",
    "awards": "Awarded for Residential Excellence (Feb-13)"
  },
  {
    "name": "Data Center building",
    "client": "International Client",
    "location": "Illinois, USA",
    "country": "USA",
    "continent": "North America",
    "lat": "40.6331",
    "lon": "-89.3985",
    "description": "Data center infrastructure project.",
    "scope of work": "",
    "image": "null",
    "awards": "Awarded for Infrastructure Excellence (Aug-12)"
  },
  {
    "name": "Material Research Laboratory",
    "client": "International Client",
    "location": "Ontario, Canada",
    "country": "Canada",
    "continent": "North America",
    "lat": "51.2538",
    "lon": "-85.3232",
    "description": "Material testing and research laboratory project.",
    "scope of work": "",
    "image": "null",
    "awards": "Awarded for Technical Excellence (Jan-12)"
  },
  {
    "name": "Aeronautical Research building",
    "client": "International Client",
    "location": "Ontario, Canada",
    "country": "Canada",
    "continent": "North America",
    "lat": "51.2538",
    "lon": "-85.3232",
    "description": "Aeronautical research laboratory project.",
    "scope of work": "",
    "image": "null",
    "awards": "Awarded for Research Excellence (Mar-12)"
  }
];